[project]
name = "traffic-imc-baseline"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Seungbin Yim", email = "ysb06@hotmail.com"},
]
dependencies = [
    "lightning>=2.3.0",
    "torch>=2.7.0",
    "numpy>=1.26.0",
    "pandas>=2.2.0",
    "pyyaml>=6.0.0",
    "scikit-learn>=1.4.0",
    "scipy>=1.11.0",
    "tqdm>=4.66.0",
    "tables>=3.9.0",
    "wandb>=0.17.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
traffic-imc = "traffic_imc_baseline.cli:main"
traffic-imc-baseline = "traffic_imc_baseline.cli:main"

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/../traffic-imc-dataset#egg=traffic-imc-dataset",
]
